version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend  # Dockerfile for the backend
    volumes:
      - ./backend:/backend  # Bind mount the backend directory for live reloading
    ports:
      - "8000:8000"  # Expose port 8000 for the backend API
    environment:
      - PYTHONPATH=/backend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000  # Allow frontend to access the backend
    command: ["python", "/backend/main.py"]  # Start the backend application
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: ./frontend  # Dockerfile for the frontend
    volumes:
      - ./frontend:/frontend  # Bind mount the frontend directory for live reloading
      - /frontend/node_modules  # Exclude node_modules from being bind mounted
    ports:
      - "3000:3000"  # Expose port 3000 for the frontend app
    environment:
      - REACT_APP_API_URL=http://backend:8000  # Use the backend service name
    command: ["npm", "run", "dev"]  # Run in development mode with live reloading
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Default network driver
