version: '3.8'

services:
  # FastAPI Backend service for both app and mana_gov
  backend_fastapi:
    build:
      context: ./backend  # Dockerfile for the FastAPI backend
    volumes:
      - ./backend:/backend  # Bind mount the backend directory
    ports:
      - "8001:8000"  # Expose port 8001 for the FastAPI backend
    environment:
      - PYTHONPATH=/backend
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]  # Start FastAPI for app and mana_gov
    networks:
      - app-network

  # Frontend Node.js service (Next.js and blockchain interactions)
  frontend_nodejs:
    build:
      context: ./frontend  # Dockerfile for the frontend with blockchain interactions
    volumes:
      - ./frontend:/frontend  # Bind mount the frontend directory
      - /frontend/node_modules:/frontend/node_modules  # Exclude node_modules from being bind mounted
    ports:
      - "3000:3000"  # Expose port 3000 for the frontend app
    environment:
      - REACT_APP_API_URL_FASTAPI=http://backend_fastapi:8001  # FastAPI backend service
    command: ["npm", "run", "dev"]  # Run Next.js frontend in development mode with live reloading
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Default network driver

